basket/urls.py
#!/usr/bin/env python
#coding:utf-8
__author__ = 'sws'

from django.conf.urls import url, static

from .views import add_to_basket, show_basket, remove_product_line

urlpatterns = [

    url(r'^add_to_basket/(?P<pk>\d+)/?$', add_to_basket, name='add_to_basket'),
    url(r'^show_basket/?$', show_basket, name='show_basket'),
    url(r'^remove_product_line/?$', remove_product_line, name='remove_product_line'),

]

category/urls.py
#!/usr/bin/env python
#coding:utf-8
__author__ = 'sws'

from django.conf.urls import url, static
from django.conf import settings

from category.views import product_detail, product_list, category_list


urlpatterns = [
   # url(r'^product_add$', )
    url(r'^product/(?P<id>\d+)/?$', product_detail, name='product_detail', ),
    url(r'^product_list/(?P<page>\d*)/?$', product_list, name="product_list"),
    url(r'^category_list/(?P<cate>\d+)/?$', category_list, name='category_list'),
]

shop/urls.py
#!/usr/bin/env python
# coding:utf-8
from django.conf.urls import include, url, static
from django.contrib import admin
from django.conf import settings

import customer.urls as customer_urls
from category.views import index
from shop.upload import upload_image
import category.urls as category_url
import basket.urls as basket_url

urlpatterns = [
    # Examples:
    # url(r'^$', 'shop.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # url

    url(r'uploads/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT,}),
    url(r'^admin/upload/(?P<dir_name>[^/]+)$',
        upload_image,name='upload_image'),

    url(r'^admin/', include(admin.site.urls)),
     # 购物车
    url(r'^basket/', include(basket_url, namespace='basket')),
    # 登录注册相关
    url(r'^customer/', include(customer_urls, namespace='customer')),
    # 分类，产品相关
    url(r'^category/', include(category_url, namespace='category')),

    # 首页
    url(r'^$', index, name="index"),
]

# urlpatterns += static(settings.MEDIA_URL, {'document_root':settings.MEDIA_ROOT,})

basket/models.py
#!/usr/bin/env python
#coding:utf-8
__author__ = 'sws'

from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import PermissionDenied

from category.models import Product

# 购物车
class Basket(models.Model):

    owner = models.ForeignKey(
        User, related_name='baskets',
        verbose_name= '拥有者'
    )

    OPEN, MERGED, SAVED, FROZEN, SUBMITTED = (
        "Open", "Merged", "Saved", "Frozen", "Submitted")
    STATUS_CHOICES = (
        (OPEN, _("Open - currently active")),
        (MERGED, _("Merged - superceded by another basket")),
        (SAVED, _("Saved - for items to be purchased later")),
        (FROZEN, _("Frozen - the basket cannot be modified")),
        (SUBMITTED, _("Submitted - has been ordered at the checkout")),
    )

    status = models.CharField(
        choices=STATUS_CHOICES, max_length=128, default=OPEN, null=True,
        verbose_name='交易状态'
    )

    date_create = models.DateTimeField(
        verbose_name='添加时间', auto_now_add=True
    )

    date_submitted = models.DateTimeField(
        '下单时间',
        null=True,
        blank=True
    )

    editable_statuses = (OPEN, SAVED)

    class Meta:
        verbose_name_plural = verbose_name = '购物车'

    def __init__(self, *args, **kwargs):
        super(Basket, self).__init__(*args, **kwargs)

        # We keep a cached copy of the basket lines as we refer to them often
        # within the same request cycle.  Also, applying offers will append
        # discount data to the basket lines which isn't persisted to the DB and
        # so we want to avoid reloading them as this would drop the discount
        # information.
        self._lines = None


    def __unicode__(self):
        return _(
            u"%(status)s basket (owner: %(owner)s, lines: %(num_lines)d)") \
               % {'status': self.status,
                  'owner': self.owner,
                  'num_lines': self.num_lines}

    def all_lines(self):
        """
        返回原来cache购物车中所有的的商品
        """
        if self.id is None:
            return self.lines.none()
        if self._lines is None:
            self._lines = (
                self.lines
                    .select_related('product__image'))
        return self._lines

    @property
    def num_lines(self):
        return self.all_lines().count()


    @property
    def can_be_edited(self):
        """
        验证是否可以编辑
        """
        return self.status in self.editable_statuses

# 交易单
class Line(models.Model):


    basket = models.ForeignKey(
        Basket, related_name='lines',
        verbose_name='购物车'
    )

    product = models.ForeignKey(
        Product, related_name='basket_lines',
        verbose_name= '商品'
    )

    quantity = models.PositiveIntegerField(
        default=1,verbose_name='数量'
    )

    date_create = models.DateTimeField(
        auto_now_add=True, verbose_name='创建时间',null=True
    )


    class Meta:
        verbose_name_plural = verbose_name = '购物商品行'
        ordering = ['-product__id']
    def __unicode__(self):
        return _(
            u"Basket #%(basket_id)d, Product #%(product_id)d, quantity"
            u" %(quantity)d") % {'basket_id': self.basket.pk,
                                 'product_id': self.product.pk,
                                 'quantity': self.quantity}

    def save(self, *args, **kwargs):
        if not self.basket.can_be_edited:
            raise PermissionDenied(
                _("You cannot modify a %s basket") % (
                    self.basket.status.lower(),))
        return super(Line, self).save(*args, **kwargs)

basket/forms.py
#!/usr/bin/env python
#coding:utf-8
__author__ = 'sws'

from django import forms


class AddToBasketForm(forms.Form):
    quantity = forms.IntegerField(initial=1, min_value=1, label="数量")

    def __init__(self, basket, product, *args, **kwargs):
        # Note, the product passed in here isn't necessarily the product being
        # added to the basket. For child products, it is the *parent* product
        # that gets passed to the form. An optional product_id param is passed
        # to indicate the ID of the child product being added to the basket.
        self.basket = basket
        self.product = product

        super(AddToBasketForm, self).__init__(*args, **kwargs)

    def clean_quantity(self):
        # Check that the proposed new line quantity is sensible
        qty = self.cleaned_data['quantity']

        if qty > self.product.store_count:
            raise forms.ValidationError(
                '超过库存量'
            )

        return qty

basket/views.py
#coding:utf-8
from datetime import datetime
import json

from django.shortcuts import render_to_response, HttpResponse
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.template import RequestContext
# Create your views here.

from category.views import index
from .models import Basket, Line
from category.models import Product
from shop.utils import try_int

@login_required(login_url='/customer/login')
def add_to_basket(request, pk):
    msg = {}

    if request.method == 'POST':
        user = request.session['is_login']
        quantity = try_int(request.POST.get('quantity', 1))
        print quantity, user
        try:
            if Basket.objects.get(owner__username=user):
                bsobj = Basket.objects.get(owner__username=user)
            else:
                bsobj = Basket.objects.create(owner=User.objects.get(username=user))
                bsobj.save()

            try:
                lineonj=Line.objects.get(product__id=pk)
            except:
                lineonj = None


            if lineonj:
                if lineonj.quantity + quantity >= lineonj.product.store_count:
                    lineonj.quantity = lineonj.product.store_count
                else:
                    lineonj.quantity = lineonj.quantity + quantity
            else:

                lineonj = Line.objects.create(
                    basket=bsobj, product=Product.objects.get(id=pk), quantity=quantity,
                    date_create=datetime.now()
                )
            lineonj.save()

        except Exception, e:
            print e
            return redirect(index)
        return redirect('basket:show_basket')

    return HttpResponseRedirect(reverse('category:product_detail', kwargs={'id':pk}))

@login_required(login_url='/customer/login')
def show_basket(request):
    msg = {}

    username = request.session.get('is_login', None)
    if username:
        msg['user'] = username
        msg['logout'] = 'Logout'

    try:
        bsobj = Basket.objects.get(owner__username=username)
    except:
        bsobj = None
    msg['basket'] = bsobj
    return render_to_response('show_basket.html', msg, context_instance=RequestContext(request))

# 删除购物车里面的商品
def remove_product_line(request):

    msg = {'status':0}

    if request.method == 'POST':
        id = request.POST.get('id', None)
        if id == None:
            return redirect(index)

        try:
            lineobj = Line.objects.get(product__id=id)
            lineobj.delete()
        except:
            return redirect(index)
        msg['status'] = 1
        return HttpResponse(json.dumps(msg))

    else:
        return redirect(index)

basket/templates/show_basket.html
{% extends 'base.html' %}
{% load mul from basket_tags %}
{% load static %}

{% block content %}
    <div class="span9">
        <ul class="breadcrumb">
            <li><a href="{% url 'index' %}">首页</a> <span class="divider">/</span></li>
            <li class="active"> 购物车</li>
        </ul>
        <h3>  购物车 [ {{ basket.num_lines }} ]
            <a href="{% url 'category:product_list' 1 %}" class="btn btn-large pull-right"><i class="icon-arrow-left"></i>
                继续购物
            </a>
        </h3>
        <hr class="soft">
    {% if basket.num_lines > 0 %}
        <table class="table table-bordered">
            <thead>
            <tr>
                <th>商品</th>
                <th>名称</th>
                <th>数量</th>
                <th>单价</th>
                <th>商品总价</th>
            </tr>
            </thead>
            {#        {% for line in basket.all_lines %}#}
            {#            {{  line.product.name}}#}
            {#        {% endfor %}#}
            <tbody>
            {% for line in basket.all_lines %}
                <tr>
                    <td> <a href="{% url 'category:product_detail' line.product.id %}">
                        <img width="60" src="{{ line.product.image.url }}" alt="">
                    </a>
                    </td>
                    <td>
                        <a href="{% url 'category:product_detail' line.product.id %}">
                            {{ line.product.name }}
                        </a>
                    <td>
                        <div class="input-append">
                            <input class='span3' type="number" size="6" placeholder="{{ line.quantity }}"
                                   min="1" max="{{ line.product.store_count }}" name="quantity_{{ line.product.id }}"/>
                            {#                            <input style="max-width:34px" placeholder="{{ line.quantity }}"#}
                            {#                                   id="appendedInputButtons" size="16" type="number" min="1" max="{{ line.product.store_count }}">#}
                            <button class="btn" type="button" onclick="minunum(this)">
                                <i class="icon-minus"></i>
                            </button>
                            <button class="btn" type="button" onclick="addnum(this)">
                                <i class="icon-plus"></i>
                            </button>
                            <button class="btn btn-danger" type="button" onclick="remove_product(this)">
                                <i class="icon-remove icon-white"></i>
                            </button>
                        </div>
                    </td>
                    <td >￥{{ line.product.retail}}</td>
                    <td id="single_product_total" >￥{{ line.product.retail|mul:line.quantity }}</td>
                </tr>
            {% endfor %}

            <tr>
                <td colspan="6" style="text-align:right"><strong>总计 =</strong></td>
                <td id="total_price" class="btn btn-default" style="display:block"> <strong> </strong></td>
            </tr>
            </tbody>
        </table>
    {% else %}
        <h2> 您还没有选购商品 </h2>
    {% endif %}
        <a href="products.html" class="btn btn-large"><i class="icon-arrow-left"></i> Continue Shopping </a>
        <a href="login.html" class="btn btn-large pull-right">Next <i class="icon-arrow-right"></i></a>
    </div>
{% endblock %}

{% block javascript %}
    // ready-------------
    $(document).ready(function(){
    calculate_total();
    }); //end ready --------------------------


    // 数量减--------------------------------------------------------------
    function minunum(doc){
    var num = $(doc).prev()[0];
    if(num.placeholder > num.min){
    num.placeholder -= 1;
    }
    calculate_single_product_total(doc, num.placeholder);
    calculate_total();
    } //end 数量减---------------------------------------------------------------------

    // 数量加---------------------------------------------------------------------
    function addnum(doc){
    var num = $(doc).prev().prev()[0];
    //console.log(num);
    if(parseInt(num.placeholder) < num.max){
    num.placeholder = parseInt(num.placeholder)+1;
    }
    calculate_single_product_total(doc, num.placeholder);
    calculate_total();
    }  //end 数量加------------------------------------------------------------------------

    // 总计---------------------------------------------------------------------
    function calculate_total(){
    con = $('td#single_product_total');
    var sum = 0.0;
    for(var i = 0; i < con.length; ++ i)
    {
    sum += parseFloat(con[i].innerHTML.slice(1));
    }
    $("td#total_price")[0].innerHTML ='￥'+sum;
    $("td#total_price")[0].style.color="red";
    } //end // 总计---------------------------------------------------------------------

    // 计算单个商品的总价钱--------------------------------------------------------------------------
    function calculate_single_product_total(doc, num){
    // console.log(num)
    var price = $(doc).parent().parent().parent().children()[3].innerHTML;
    var total_price = $(doc).parent().parent().parent().children()[4];
    total_price.innerHTML = price[0]+parseFloat(price.slice(1))*num;
    //console.log(parseFloat(price[1]));
    }// end 计算单个商品的总价钱--------------------------------------------------------------------------

    // 删除购物车中的商品---------------------------------------------------------------
    function remove_product(doc){
        var paren = $(doc).parent().parent().parent()[0];
        var id = $(doc).prev().prev().prev()[0]['name'].split('_')[1];
        paren.remove();
        console.log(id);

        $.ajax({
            url: "{% url 'basket:remove_product_line' %}",
            data:{
                id:id,
                csrfmiddlewaretoken: $.cookie('csrftoken'),
            },
            type:'POST',
            success:function(callback){
                var temp = jQuery.parseJSON(callback);
                if(temp.status == 1){
                    paren.remove();
                }

                calculate_total();
                console.log(jQuery.parseJSON(callback));//paren.remove();
            }
        })
    }// end 删除购物车中的商品---------------------------------------------------------------

{% endblock %}

{% block script %}
    <script type="text/javascript" src="{% static 'js/jquery/jquery.cookie.js' %}"></script>
{% endblock %}