basket/urls.py
#!/usr/bin/env python
#coding:utf-8
__author__ = 'sws'

from django.conf.urls import url, static

from .views import add_to_basket, show_basket, remove_product_line

urlpatterns = [

    url(r'^add_to_basket/(?P<pk>\d+)/?$', add_to_basket, name='add_to_basket'),
    url(r'^show_basket/?$', show_basket, name='show_basket'),
    url(r'^remove_product_line/?$', remove_product_line, name='remove_product_line'),

]

category/urls.py
#!/usr/bin/env python
#coding:utf-8
__author__ = 'sws'

from django.conf.urls import url, static
from django.conf import settings

from category.views import product_detail, product_list, category_list


urlpatterns = [
   # url(r'^product_add$', )
    url(r'^product/(?P<id>\d+)/?$', product_detail, name='product_detail', ),
    url(r'^product_list/(?P<page>\d*)/?$', product_list, name="product_list"),
    url(r'^category_list/(?P<cate>\d+)/?$', category_list, name='category_list'),
]

customer/urls.py
#!/usr/bin/env python
#coding:utf-8
__author__ = 'sws'

from django.conf.urls import url


from customer.views import index, registration, login, logout
urlpatterns = [
    url(r"^login/$", login, name='login'),
    url(r'^regisration/$', registration, name='registration'),
    # url(r'^forgetpassword/$', forgetpassword, name='forgetpassword'),
    url(r'^logout', logout, name='logout')
]

shop/urls.py
#!/usr/bin/env python
# coding:utf-8
from django.conf.urls import include, url, static
from django.contrib import admin
from django.conf import settings

import customer.urls as customer_urls
from category.views import index
from shop.upload import upload_image
import category.urls as category_url
import basket.urls as basket_url

urlpatterns = [
    # Examples:
    # url(r'^$', 'shop.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # url

    url(r'uploads/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT,}),
    url(r'^admin/upload/(?P<dir_name>[^/]+)$',
        upload_image,name='upload_image'),

    url(r'^admin/', include(admin.site.urls)),
     # 购物车
    url(r'^basket/', include(basket_url, namespace='basket')),
    # 登录注册相关
    url(r'^customer/', include(customer_urls, namespace='customer')),
    # 分类，产品相关
    url(r'^category/', include(category_url, namespace='category')),

    # 首页
    url(r'^$', index, name="index"),
]

# urlpatterns += static(settings.MEDIA_URL, {'document_root':settings.MEDIA_ROOT,})

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Bootshop online Shopping cart</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap style -->
    <link id="callCss" rel="stylesheet" href="{% static "themes/bootshop/bootstrap.min.css" %}" media="screen"/>
    <link href="{% static "themes/css/base.css" %}" rel="stylesheet" media="screen"/>
    <!-- Bootstrap style responsive -->
    <link href="{% static "themes/css/bootstrap-responsive.min.css" %}" rel="stylesheet"/>
    <link href="{% static "themes/css/font-awesome.css" %}" rel="stylesheet" type="text/css">
    <!-- Google-code-prettify -->
    <link href="{% static "themes/js/google-code-prettify/prettify.css" %}" rel="stylesheet"/>
    <!-- fav and touch icons -->
    <link rel="shortcut icon" href="{% static "themes/images/ico/favicon.ico" %}">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static "themes/images/ico/apple-touch-icon-144-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static "themes/images/ico/apple-touch-icon-114-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static "themes/images/ico/apple-touch-icon-72-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" href="{% static "themes/images/ico/apple-touch-icon-57-precomposed.png" %}">
    <style type="text/css" id="enject"></style>
</head>
<body>
<div id="header">
    <div class="container">

        <div id="welcomeLine" class="row">
            <div class="span6">Welcome!<strong>
                {% if user %}
                    {{ user }}
                {% else %}
                    AnonymousUser
                {% endif %}

            </strong></div>
            <div class="span6">
                <div class="pull-right">
                    <a href="{% url 'basket:show_basket' %}">
                        <span class="btn btn-mini btn-primary">
                            <i class="icon-shopping-cart icon-white"></i>

                            [
                            {% if basket %}{{ basket.num_lines }}{% else %} 0 {% endif %}
                            ] 件商品在购物车 </span> </a>


                </div>
            </div>
        </div>
        <!-- Navbar ================================================== -->
        <div id="logoArea" class="navbar">
            <a id="smallScreen" data-target="#topMenu" data-toggle="collapse" class="btn btn-navbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div class="navbar-inner">
                <a class="brand" href="{% url 'index' %}"><img src="{% static "themes/images/logo.png" %}" alt="Bootsshop"/></a>
                <form class="form-inline navbar-search" method="get" action="" >
                    <input id="srchFld" class="srchTxt" type="text" />
                    <select class="srchTxt">
                        <option>All</option>
                        <option>CLOTHES </option>
                        <option>FOOD AND BEVERAGES </option>
                        <option>HEALTH & BEAUTY </option>
                        <option>SPORTS & LEISURE </option>
                        <option>BOOKS & ENTERTAINMENTS </option>
                    </select>
                    <button type="submit" id="submitButton" class="btn btn-primary">Go</button>
                </form>
                <ul id="topMenu" class="nav pull-right">
                    <li class=""><a href="{% url 'category:product_list' 1 %}">商品列表</a></li>
                    <li class=""><a href="{% url 'basket:show_basket' %}">购物车</a></li>
                    <li class="">
                        {% if not logout %}
                            <a href="{% url 'customer:login' %}" role="button" data-toggle="modal" style="padding-right:0"><span class="btn btn-large btn-success">Login</span></a>
                        {% else %}
                            <a href="{% url 'customer:logout' %}" role="button" data-toggle="modal" style="padding-right:0"><span class="btn btn-large btn-success">{{ logout }}</span></a>

                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<!-- Header End====================================================================== -->
<div id="carouselBlk">
    <div id="myCarousel" class="carousel slide">
        <div class="carousel-inner">
            <div class="item active">
                <div class="container">
                    <a href='javascript:;'><img style="width:100%" src="{% static "themes/images/carousel/1.png" %}" alt="special offers"/></a>
                </div>
            </div>
            <div class="item">
                <div class="container">
                    <a href="javascript:;"><img style="width:100%" src="{% static "themes/images/carousel/2.png" %}" alt=""/></a>
                </div>
            </div>
            <div class="item">
                <div class="container">
                    <a href="javascript:;"><img src="{% static "themes/images/carousel/3.png" %}" alt=""/></a>
                </div>
            </div>
            <div class="item">
                <div class="container">
                    <a href="javascript:;"><img src="{% static "themes/images/carousel/4.png" %}" alt=""/></a>
                </div>
            </div>
            <div class="item">
                <div class="container">
                    <a href="javascript:;"><img src="{% static "themes/images/carousel/5.png" %}" alt=""/></a>
                </div>
            </div>
            <div class="item">
                <div class="container">
                    <a href="javascript:;"><img src="{% static "themes/images/carousel/6.png" %}" alt=""/></a>
                </div>
            </div>
        </div>
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
</div>
<div id="mainBody">
    <div class="container">
        <div class="row">
            <!-- Sidebar ================================================== -->
            <div id="sidebar" class="span3">
                {% block side_content %} {% endblock %}
                <div id="sidebar" class="span3">
                    <div class="well well-small"><a id="myCart" href="{% url 'basket:show_basket' %}">
                        <img src="{% static "themes/images/ico-cart.png" %}" alt="cart">
                         [
                            {% if basket %}{{ basket.num_lines }}{% else %} 0 {% endif %}
                            ] 件商品在购物车
                        </a></div>
                    {% block side_menu %}{% endblock %}
                    <br/>
                    <div class="thumbnail">
                        <img src="{% static "themes/images/products/panasonic.jpg" %}" alt="Bootshop panasonoc New camera"/>
                        <div class="caption">
                            <h5>Panasonic</h5>
                            <h4 style="text-align:center"><a class="btn" href="product_details.html"> <i class="icon-zoom-in"></i></a> <a class="btn" href="#">Add to <i class="icon-shopping-cart"></i></a> <a class="btn btn-primary" href="#">$222.00</a></h4>
                        </div>
                    </div><br/>
                    <div class="thumbnail">
                        <img src="{% static "themes/images/products/kindle.png" %}" title="Bootshop New Kindel" alt="Bootshop Kindel">
                        <div class="caption">
                            <h5>Kindle</h5>
                            <h4 style="text-align:center"><a class="btn" href="product_details.html"> <i class="icon-zoom-in"></i></a> <a class="btn" href="#">Add to <i class="icon-shopping-cart"></i></a> <a class="btn btn-primary" href="#">$222.00</a></h4>
                        </div>
                    </div><br/>
                    <div class="thumbnail">
                        <img src="{% static "themes/images/payment_methods.png" %}" title="Bootshop Payment Methods" alt="Payments Methods">
                        <div class="caption">
                            <h5>Payment Methods</h5>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Sidebar end=============================================== -->
            {# content ---- #}
            <div class="span9">
                {% block content %} {% endblock %}
                {#                {% for product  %}#}
            </div>
            {# -------end content #}
        </div>
    </div>
</div>
<!-- Footer ================================================================== -->
<div  id="footerSection">
    <div class="container">
        <div class="row">
            <div class="span3">
                <h5>ACCOUNT</h5>
                <a href="login.html">YOUR ACCOUNT</a>
                <a href="login.html">PERSONAL INFORMATION</a>
                <a href="login.html">ADDRESSES</a>
                <a href="login.html">DISCOUNT</a>
                <a href="login.html">ORDER HISTORY</a>
            </div>
            <div class="span3">
                <h5>INFORMATION</h5>
                <a href="contact.html">CONTACT</a>
                <a href="register.html">REGISTRATION</a>
                <a href="legal_notice.html">LEGAL NOTICE</a>
                <a href="tac.html">TERMS AND CONDITIONS</a>
                <a href="faq.html">FAQ</a>
            </div>
            <div class="span3">
                <h5>OUR OFFERS</h5>
                <a href="#">NEW PRODUCTS</a>
                <a href="#">TOP SELLERS</a>
                <a href="special_offer.html">SPECIAL OFFERS</a>
                <a href="#">MANUFACTURERS</a>
                <a href="#">SUPPLIERS</a>
            </div>
            <div id="socialMedia" class="span3 pull-right">
                <h5>SOCIAL MEDIA </h5>
                <a href="#"><img width="60" height="60" src="{% static "themes/images/facebook.png" %}" title="facebook" alt="facebook"/></a>
                <a href="#"><img width="60" height="60" src="{% static "themes/images/twitter.png" %}" title="twitter" alt="twitter"/></a>
                <a href="#"><img width="60" height="60" src="{% static "themes/images/youtube.png" %}" title="youtube" alt="youtube"/></a>
            </div>
        </div>
        <p class="pull-right">&copy; Bootshop</p>
    </div><!-- Container End -->
</div>
<!-- Placed at the end of the document so the pages load faster ============================================= -->
<script src="{% static "themes/js/jquery.js" %}" type="text/javascript"></script>
<script src="{% static "themes/js/bootstrap.min.js" %}" type="text/javascript"></script>
<script src="{% static "themes/js/google-code-prettify/prettify.js" %}"></script>

<script src="{% static "themes/js/bootshop.js" %}"></script>
<script src="{% static "themes/js/jquery.lightbox-0.5.js" %}"></script>

{# ------javascript #}
{% block script %}{% endblock %}
{# ------endjavascript #}
<script type="text/javascript">
    {% block javascript %}{% endblock %}
</script>

</body>
</html>

templates/error.html
{% extends 'index.html' %}

{% block content%}
    <h1>There has something wrong</h1>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load set getchildren from tmptags  %}

{% block content %}

    {#                  展示商品   #}

    <div class="item">
        <ul class="thumbnails">
            {% for product in product_list %}
                <li class="span3">
                    <div class="thumbnail">
                        <a  href="{% url 'category:product_detail' product.id %}"><img src="{{ product.image.url }}" alt=""/></a>
                        <div class="caption">
                            <h5>{{ product.name }}</h5>
                            <p>
                                {{ product.summary }}
                            </p>

                            <h4 style="text-align:center">
                                <a class="btn" href="{% url 'category:product_detail' product.id %}"> <i class="icon-zoom-in"></i></a>

                                <span class="btn btn-primary" href="#">￥{{ product.retail }}</span>
                                <form action="{% url 'basket:add_to_basket' product.id %}" method="post" name="add_to_basket">
                                    {% csrf_token %}
                                    <input type="hidden" value="1" name="quantity"/>
                                    <button class="btn btn-primary" data-loading-text="添加中.."> 加入购物车</button>
                                </form>
                            </h4>

                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
    {% autoescape off %}
        {{ paginator }}
    {% endautoescape %}
{% endblock %}


{% block side_menu %}

    {% set a = 1 %}
    <ul d="sideManu" class="nav nav-tabs nav-stacked">
    {% for cate in cate_list %}
        {% if a == 1 %}
            <li class="subMenu open"><a> {{ cate.name }}</a>
            <ul>
            {% set a = 0 %}
        {% else %}
            <li class="subMenu"><a> {{ cate.name }}</a>
            <ul style="display:none">
        {% endif %}



    {% for child in cate|getchildren %}
        {#                <li><a class="active" href="products.html"><i class="icon-chevron-right"></i>{{ child.name }} </a></li>#}
        <li><a href="{% url 'category:category_list' child.id %}"><i class="icon-chevron-right"></i>{{ child.name }}</a></li>

    {% endfor %}
    </ul>
    </li>

    {% endfor %}
</ul>
{% endblock %}