customer/urls.py
#!/usr/bin/env python
#coding:utf-8
__author__ = 'sws'

from django.conf.urls import url


from customer.views import index, registration, login, logout
urlpatterns = [
    url(r"^login/$", login, name='login'),
    url(r'^regisration/$', registration, name='registration'),
    # url(r'^forgetpassword/$', forgetpassword, name='forgetpassword'),
    url(r'^logout', logout, name='logout')
]

shop/urls.py
#!/usr/bin/env python
# coding:utf-8
from django.conf.urls import include, url, static
from django.contrib import admin
from django.conf import settings

import customer.urls as customer_urls
from category.views import index
from shop.upload import upload_image
import category.urls as category_url
import basket.urls as basket_url

urlpatterns = [
    # Examples:
    # url(r'^$', 'shop.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # url

    url(r'uploads/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT,}),
    url(r'^admin/upload/(?P<dir_name>[^/]+)$',
        upload_image,name='upload_image'),

    url(r'^admin/', include(admin.site.urls)),
     # 购物车
    url(r'^basket/', include(basket_url, namespace='basket')),
    # 登录注册相关
    url(r'^customer/', include(customer_urls, namespace='customer')),
    # 分类，产品相关
    url(r'^category/', include(category_url, namespace='category')),

    # 首页
    url(r'^$', index, name="index"),
]

# urlpatterns += static(settings.MEDIA_URL, {'document_root':settings.MEDIA_ROOT,})

customer/forms.py
#!/usr/bin/env python
#coding:utf-8
__author__ = 'sws'

import random
import string

from django import forms
from django.conf import settings
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.utils.http import is_safe_url
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import pgettext_lazy

from customer.utils import password_validators, get_right_user
# from customer.models import User

from django.contrib.auth.models import User

def generate_username():
    # Python 3 uses ascii_letters. If not available, fallback to letters
    try:
        letters = string.ascii_letters
    except AttributeError:
        letters = string.letters
    uname = ''.join([random.choice(letters + string.digits + '_')
                     for i in range(30)])
    try:
        User.objects.get(username=uname)
        return generate_username()
    except User.DoesNotExist:
        return uname


class UserLoginForm(forms.Form):
    accountname = forms.CharField(label='用户名/邮箱', min_length=1,

    )
    password = forms.CharField(
        label = _('Password'), widget=forms.PasswordInput,
        validators = password_validators
    )

    def clean_accountname(self):
        accountname = self.cleaned_data.get('accountname', '')

        if not (User.objects.filter(email__iexact=accountname).exists()
                    or User.objects.filter(username__iexact=accountname).exists()):
            raise  forms.ValidationError(
                '用户名或邮箱不存在'
            )
        return accountname

    def clean_password(self):
        accountname = self.cleaned_data.get('accountname', '')
        pwd = self.cleaned_data.get('password', '')
        user = get_right_user(accountname=accountname, pwd=pwd)
        if user is None:
            raise forms.ValidationError(
                '账号或密码错误'
            )
        return pwd




class EmailUserCreationForm(forms.ModelForm):
    username = forms.CharField(label=_('username'))
    email = forms.EmailField(label='邮箱')
    password1 = forms.CharField(
        label = _('Password'), widget=forms.PasswordInput,
        validators = password_validators
    )
    password2 = forms.CharField(
        label='确认密码', widget=forms.PasswordInput
    )


    class Meta:
        model=User
        fields = ('email', 'username',)

    def clean_email(self):
        email = self.cleaned_data['email']

        if User.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError(
                "邮箱已存在"
            )
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1', '')
        password2 = self.cleaned_data.get('password2', '')
        if password1 != password2:
            raise  forms.ValidationError(
                # _('The password mismatch the former one.')
                '密码不一致'
            )

customer/views.py
#!/usr/bin/env python
#coding:utf8

import json

from django.shortcuts import render_to_response, redirect, render
from django.views.generic import TemplateView, RedirectView
from django.conf import settings
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from django.contrib.auth import  authenticate, logout as auth_logout, login as auth_login
from django.template.context import RequestContext
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


from customer.forms import EmailUserCreationForm, UserLoginForm
from customer.mixin import RegisterUserMixin
from category.views import index

from customer.utils import get_right_user
from shop.utils import try_int
# from customer.models import User
# Create your views here.

class LogOutView(RedirectView):
    url = settings.LOGIN_REDIRECT_URL
    permanent = False

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        response = super(LogOutView, self).get(*args, **kwargs)

        return response


def login(request):

    next_url = request.GET.get('next', None)

    msg = {}
    msg['next_url'] = next_url
    msg['registration_form'] = EmailUserCreationForm()
    if request.method == 'POST':
        nex = request.POST.get('next_url', None)
        # print nex
        form = UserLoginForm(request.POST)
        if form.is_valid():
            accountname = form.cleaned_data['accountname']
            pwd = form.cleaned_data['password']


            # 登陆
            user = get_right_user(accountname, pwd)
            if user:
                auth_login(request, user=user)

            request.session['is_login'] = user.username
            if nex != 'None':

                temp = nex.split('/') #处理next_url
                print temp[-1]
                if temp[-1] != u'' and len(temp) == 4:
                    return redirect(reverse('%s:%s' %(temp[1],temp[2]), kwargs={'pk':try_int(temp[3])}))
                else:
                    return redirect(reverse('%s:%s' %(temp[1],temp[2]), kwargs={}))
            else:
                return redirect(index)
        else:
            msg['login_form'] = form
            return render_to_response('login_registration.html', msg, context_instance=RequestContext(request))


    msg['login_form'] = UserLoginForm()

    return render_to_response('login_registration.html', msg, context_instance=RequestContext(request))

def registration(request):
    msg = {}
    msg['login_form'] = UserLoginForm()
    if request.method == 'POST':
        # print type(request.POST)
        formss = EmailUserCreationForm(request.POST)

        # print formss.is_bound
        if formss.is_valid():
            cleaned_data = formss.cleaned_data
            username = cleaned_data['username']
            email = cleaned_data['email']

            pwd = cleaned_data['password1']
            user = User.objects.create_user(username=username,
                                            email=email,
                                            password=pwd)
            user.save()
            request.session['is_login'] = username
            return redirect(index)
        else:
            print 's'
            msg['registration_form'] = formss
            return render_to_response('login_registration.html', msg, context_instance=RequestContext(request))

    msg['registration_form'] = EmailUserCreationForm()


    return render_to_response('login_registration.html', msg, context_instance=RequestContext(request))

def logout(request):
    request.session['is_login'] = None
    auth_logout(request)
    return redirect(index)

customer/templates/login_registration.html
{% extends "base.html" %}
{% load staticfiles %}
{% load static %}
{% load i18n %}



{% block content %}


    <ul class="breadcrumb">
        <li><a href="{% url 'index' %}">Home</a> <span class="divider">/</span></li>
        <li class="active">Login</li>
    </ul>
    <h3> Login</h3>
    <hr class="soft"/>

    <div class="row">
        <div class="span4">
            <div class="well">
                <h5>已经注册？</h5>
                <form action="{% url 'customer:login' %}" method="post">
                    {% csrf_token %}
                    {% if login_form.non_field_errors %}
                        {% for error in login_form.name_field_errors %}
                            <div class="alert alert-danger">
                                <i class="icon-exclamation-sign"></i> {{ error }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% for error in field.errors %}
                        <span class="error-block"><i class="icon-exclamation-sign"></i> {{ error }}</span>
                    {% endfor %}

                    {% for field in login_form %}
                        {% if field.is_hidden %}
                            {{ field }}
                        {% else %}

                            <div class="control-group">
                                <label class="control-label" for="{{ field.label }}" id="{{ field.id_for_label }}">{{ field.label }}</label>
                                <div class="controls">
                                    {{ field }}
                                </div>
                                {% if field.errors %}
                                    <div class="alert alert-error">{{ field.errors }}</div>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                    <input type="hidden", name="next_url", value="{{ next_url }}">
                    <div class="controls">
                        {#                <button type="submit" class="btn block">注册</button>#}
                        <button name="login_submit" type="submit" value="login" class="btn btn-lg btn-primary" data-loading-text="正在登陆中">登陆</button>
                    </div>
                </form>
            </div>
        </div>

        <div class="span1"> &nbsp;</div>
        <div class="span4">
            <div class="well">
                <h5>注册账户？</h5><br/>

                <form action="{% url 'customer:registration' %}" method="post">
                    {% csrf_token %}
                    {% if registration_form.non_field_errors %}
                        {% for error in registration_form.name_field_errors %}
                            <div class="alert alert-danger">
                                <i class="icon-exclamation-sign"></i> {{ error }}
                            </div>
                        {% endfor %}
                    {% endif %}
                    {% for error in field.errors %}
                        <span class="error-block"><i class="icon-exclamation-sign"></i> {{ error }}</span>
                    {% endfor %}

                    {% for field in registration_form %}
                        {% if field.is_hidden %}
                            {{ field }}
                        {% else %}

                            <div class="control-group">
                                <label class="control-label" for="{{ field.label }}" id="{{ field.id_for_label }}">{{ field.label }}</label>
                                <div class="controls">
                                    {{ field }}
                                </div>
                                {% if field.errors %}
                                    <div class="alert alert-error">{{ field.errors }}</div>
                                {% endif %}
                            </div>
                        {% endif %}
                    {% endfor %}
                    <input type="hidden", name="next_url", value="{{ next_url }}">
                    <div class="controls">
                        {#                <button type="submit" class="btn block">注册</button>#}
                        <button name="registration_submit" type="submit" value="Register" class="btn btn-lg btn-primary" data-loading-text="正在注册中">注册</button>
                    </div>
                </form>
            </div>
        </div>
    </div>


{% endblock content %}

{% block script %}
    <script src="{% static "js/jquery/jquery-1.9.1.min.js" %}"
{% endblock %}

{% block javascript %}
    {#    $.ajax({#}
    {##}
    {#    })#}
{% endblock %}